---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkinscred
  namespace: jenkins
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjp7CiAgICAgICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6ewogICAgICAgICAgICAiYXV0aCI6ImRtVnVkV0pvWVhKaFpIZGhhanBUYm1Wb1lVQXhNak09IgogICAgICAgIH0KCiAgICB9Cgp9
type: kubernetes.io/dockerconfigjson
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: jenkins
    name: jenkins-image
  spec:
    selector:
      matchLabels:
        app: jenkins-app
    template:
      metadata:
        namespace: jenkins
        labels:
          app: jenkins-app
      spec:
        containers:
        - name: jenkins-image
          image: jenkins:2.32.1
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "200m"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
        imagePullSecrets:
              - name:  jenkinscred
---
  kind: Service
  apiVersion: v1
  metadata:
    name: jenkins
    namespace: jenkins
  spec:
    selector:
      app:  jenkins-app
    type:   NodePort
    ports:
    - name:  jenkinsport
      port:  8080
      targetPort:  8080